<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageId>YLFramework.DynamicApi</PackageId>
		<Description>中台动态 WebApi 库（约定式路由 + 统一结果格式化）</Description>
		<PackageTags>DynamicApi;WebApi;AspNetCore;Mvc;</PackageTags>
		<SignAssembly>False</SignAssembly>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>