<Project>
  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
    <PackageReference Include="FreeSql" Version="3.5.311" />
    <PackageReference Include="FreeSql.DbContext" Version="3.5.311" />
    <PackageReference Include="FreeSql.Repository" Version="3.5.311" />
    <PackageReference Include="Mapster" Version="10.0.11" />
    <PackageReference Include="System.Text.Json" Version="10.0.11" />
    <PackageReference Include="Yitter.IdGenerator" Version="1.0.15" />
  </ItemGroup>
</Project>
