<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="Framework.ZLogging.Tests.Packages.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TestingPlatformCaptureOutput>false</TestingPlatformCaptureOutput>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Framework.ZLogging\Framework.ZLogging.csproj" />
  </ItemGroup>
</Project>
